name: Check PR

on:
  pull_request:
    branches: [ main ]

jobs:
  run:
    name: Run type check, linters and tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.12.0]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies (with cache)
      uses: bahmutov/npm-install@v1

    - name: Check types
      run: pnpm type-check

    - name: Check linting
      run: pnpm lint

    - name: Run tests
      run: pnpm test
